#include "selfdrive/ui/bluepilot/qt/offroad/routes_panel/segment_index.h"

#include <QDir>
#include <QFileInfo>
#include "selfdrive/ui/bluepilot/bp_logging.h"

namespace {
constexpr int64_t kSegmentDurationMs = 60000;  // Approximate 1-minute segments

// STOP AND READ THIS FIRST - THIS IS VERY IMPORTANT
// This is the structure of the routes directory on the device and the desktop cache

// Root directory: routes live under `/data/media/0/realdata` on device and the
// equivalent `~/comma_data/media/0/realdata` when running locally.

// Naming pattern:
//   <route-base>
//     └── <route-base>--<segment-index>
//           ├── fcamera.hevc      (front HDR road camera)
//           ├── ecamera.hevc      (wide road camera)
//           ├── dcamera.hevc      (driver camera)
//           ├── qcamera.ts        (legacy low-res front camera)
//           ├── rlog.zst / qlog.zst (logs; sometimes only present in the root)
//           └── ... other metadata generated by loggerd (timestamps.json, etc.)

// Example (base route `000000a1--70bc3cfd0f`):
//   /data/media/0/realdata/
//     000000a1--70bc3cfd0f--0
//     000000a1--70bc3cfd0f--1
//     000000a1--70bc3cfd0f--2

// Legacy code occasionally uses the base name without the trailing `--<n>`
// suffix.  The new pipeline always resolves the concrete segment directories
// via `SegmentIndex`, using the glob `<route-base>--*` to discover all segments.
// Camera-specific files are selected by `SegmentBuffer::videoPath()`.
}

SegmentIndex::SegmentIndex() = default;
SegmentIndex::~SegmentIndex() = default;

bool SegmentIndex::loadRoute(const QString &route_id, const QString &routes_dir) {
  route_id_ = route_id;
  routes_dir_ = routes_dir;
  segments_.clear();
  total_duration_ms_ = 0;

  const QString base_path = routes_dir_ + "/" + route_id_;

  QDir route_dir(base_path);
  QStringList segment_dirs;

  if (route_dir.exists()) {
    // Route directory exists as a base directory, look for segment subdirectories
    segment_dirs = route_dir.entryList({route_id_ + "--*"}, QDir::Dirs | QDir::NoDotAndDotDot);
  } else {
    // Route directory doesn't exist as base, look for segment directories in parent
    QDir parent_dir(routes_dir_);
    segment_dirs = parent_dir.entryList({route_id_ + "--*"}, QDir::Dirs | QDir::NoDotAndDotDot);
  }

  segment_dirs.sort();
  if (segment_dirs.isEmpty()) {
    BPLog::bpWarn() << "[bp.video.segment_index] loadRoute | no segments for route: " << route_id_.toStdString() << " under " << routes_dir_.toStdString() << std::endl;
    return false;
  }

  BPLog::bpDebugVideo() << "[bp.video.segment_index] loadRoute | discovered " << segment_dirs.size() << " segments for route:" << route_id_.toStdString() << std::endl;

  int64_t current_start_ms = 0;
  for (const QString &segment_dir : segment_dirs) {
    QString segment_path;
    if (route_dir.exists()) {
      // Segments are subdirectories of the route directory
      segment_path = routes_dir_ + "/" + route_id_ + "/" + segment_dir;
    } else {
      // Segments are in the parent directory
      segment_path = routes_dir_ + "/" + segment_dir;
    }

    QDir seg_dir(segment_path);
    const QStringList video_files = seg_dir.entryList({"*.hevc", "*.ts"}, QDir::Files);
    if (video_files.isEmpty()) {
      BPLog::bpWarn() << "[bp.video.segment_index] loadRoute | segment missing video files: " << segment_path.toStdString() << std::endl;
      continue;
    }

    SegmentInfo info;
    info.path = segment_path;
    info.start_ms = current_start_ms;
    info.duration_ms = kSegmentDurationMs;
    segments_.push_back(info);
    current_start_ms += kSegmentDurationMs;
  }

  total_duration_ms_ = current_start_ms;
  BPLog::bpDebugVideo() << "[bp.video.segment_index] loadRoute | initialized " << segments_.size() << " segments total: " << total_duration_ms_ << "ms" << std::endl;
  return !segments_.empty();
}

std::tuple<int, int64_t> SegmentIndex::lookupGlobalMs(int64_t global_ms) const {
  if (segments_.empty()) {
    return {0, 0};
  }

  if (global_ms < 0) {
    return {0, 0};
  }

  if (global_ms >= total_duration_ms_) {
    const int last_idx = static_cast<int>(segments_.size()) - 1;
    return {last_idx, segments_[last_idx].duration_ms - 1};
  }

  for (int i = 0; i < static_cast<int>(segments_.size()); ++i) {
    const SegmentInfo &segment = segments_[i];
    const int64_t segment_end_ms = segment.start_ms + segment.duration_ms;
    if (global_ms >= segment.start_ms && global_ms < segment_end_ms) {
      const int64_t local_ms = global_ms - segment.start_ms;
      return {i, local_ms};
    }
  }

  const int last_idx = static_cast<int>(segments_.size()) - 1;
  return {last_idx, segments_[last_idx].duration_ms - 1};
}

int SegmentIndex::segmentForMs(int64_t global_ms) const {
  return std::get<0>(lookupGlobalMs(global_ms));
}

int64_t SegmentIndex::getGlobalMs(int segment_idx, int64_t local_ms) const {
  if (segment_idx < 0 || segment_idx >= static_cast<int>(segments_.size())) {
    return 0;
  }
  const SegmentInfo &segment = segments_[segment_idx];
  return segment.start_ms + local_ms;
}

QString SegmentIndex::getSegmentPath(int segment_idx) const {
  if (segment_idx < 0 || segment_idx >= static_cast<int>(segments_.size())) {
    return QString();
  }
  return segments_[segment_idx].path;
}

int64_t SegmentIndex::totalDurationMs() const {
  return total_duration_ms_;
}

int SegmentIndex::totalSegments() const {
  return static_cast<int>(segments_.size());
}
